spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: cloud-config-wangcc-dev  
---
spring:
  profiles: test
  application:
    name: cloud-config-wangcc-test  
#请保存为UTF-8   
